// AUTO-GENERATED by scripts/inspect-logos.mjs — do not edit by hand.
// Maps logo filename → dominant background colour (sampled from the four
// corner pixels). GuestCard uses this to tint the logo badge so coloured-
// background logos (mesdarons, openclassrooms2, …) don't sit inside a white
// rectangle. Re-run `node scripts/inspect-logos.mjs` after uploading new
// logos.

export const LOGO_BG_COLORS: Record<string, string> = {
  "ABtasty.png": "#3100be",
  "HomeExchange.png": "#f7a800",
  "Mirakl.png": "#0d2142",
  "WTTJ.png": "#ffcd00",
  "adeo.png": "#a6a696",
  "maria2.png": "#ffcd00",
  "mesdarons.webp": "#c86d4c",
  "noe.png": "#4252ff",
  "openclassrooms2.jpg": "#7451eb",
  "pluee.png": "#221c46",
};
